name: sales_ai_examples
description: "An e-commerce shoe store featuring an AI personalized assistant."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.3
  dio: ^5.4.3+1
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.0
  firebase_ui_auth: ^1.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_markdown: ^0.7.1
  flutter_stripe: ^10.1.1
  flutter_tts: ^4.0.2
  go_router: ^14.1.2
  google_generative_ai: ^0.4.0
  pay: ^2.0.0
  permission_handler: ^11.3.1
  speech_to_text: ^6.6.1
  video_player: ^2.8.6
  webview_flutter: ^4.8.0
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    # - assets/data/
    - assets/videos/
  
  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
